"""Synthetic fixture builder for the hemp decorticator
validation pack (Phase 17.4).

Per spec §12.4, the validation pack is "generated by the
maintainer or the user, not by the platform. For v1, the
pack is synthetic." This script is the synthesizer: it
emits 6 A3-sized PDF fixtures and 6 placeholder sidecar
files for the regression suite
(``tests/test_hemp_decorticator_validation_pack.py``).

The script is **not** called by CI. It is a maintainer
tool. To re-generate the pack after a code change that
affects the validation contract:

    python tests/fixtures/build_synthetic_fixtures.py

**The 6 subsystems** (canonical keys from
``app.vision.machine_graph_builder._SUBSYSTEM_KEYWORDS``):

    hopper, conveyor, compression_rollers, drum, spindle, frame

Each fixture PDF has a hand-typeset title block (with the
machine name, drawing number, revision, material, date),
a BOM line (with the subsystem keyword + a material +
optional mass), and a small set of dimension annotations
(Ø, R, THK, LENGTH). The text is embedded in the PDF
content stream so pdfplumber can extract it on
environments where the library is installed; in
environments without pdfplumber, the chain degrades
gracefully (the orchestrator adapter is mocked in the
regression test, so the absence of OCR is not a
blocker).

**Sidecar contract:**

- ``expected/<name>.graph.json`` — the canonical
  MachineGraph the platform must produce for this
  fixture. The test asserts the platform's actual
  graph is a superset of these nodes (over-extraction
  is allowed; under-extraction fails per spec §5.1).

- ``expected/<name>.score.txt`` — a single float, the
  minimum composite score for a passing run. The
  initial value is the literal string ``TBD`` (the
  maintainer must run the manual reference config
  through the orchestrator, record the composite
  score, and subtract 0.10 per spec §5.1 to get the
  sidecar threshold).

**Why the script computes xref offsets programmatically:**

The hand-stamped xref offsets in
``tests/test_drawing_ingest_e2e.py::MINIMAL_PDF_BYTES``
work for that single fixed-size PDF. This script
synthesizes 6 PDFs with different embedded text
lengths, so the offsets differ per fixture. The
script computes the offsets by walking the object
table once the content stream is built.

**Why no real CAD drawings:**

The spec is explicit (§12.4) that the v1 pack is
synthetic. Real drawings will be added in v1.1+ when
the maintainer has access to client-supplied
fabrication drawings.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Dict, List


# ---------------------------------------------------------------------------
# Subsystem fixture data
# ---------------------------------------------------------------------------
#
# Each entry carries the text-embedded content that the
# OCR pipeline will see when the PDF is processed. The
# text is shaped to:
#   1. Match the title-block regex in
#      app.vision.titleblock_parser (MACHINE/TITLE lines).
#   2. Match the BOM-row heuristic in
#      app.vision.bom_reader (subsystem keyword +
#      material + optional mass).
#   3. Match the dimension-annotation regexes in
#      app.vision.dimension_reader (Ø, R, THK, LENGTH).
#   4. Match the assembly-detector keyword scan
#      (the subsystem keyword appears in the text).


_SUBSYSTEM_FIXTURES: List[Dict] = [
    {
        "name": "hopper",
        "filename": "hopper_a3.pdf",
        "drawing_number": "DWG-HOP-001",
        "title": "HOPPER A3 SHEET 1",
        "subsystem_keyword": "Hopper",
        "material": "MILD STEEL",
        "bom_lines": [
            "1  Hopper Mild Steel 45 KG",
        ],
        "dimension_lines": [
            "TOP WIDTH 500",
            "BOTTOM WIDTH 150",
            "HEIGHT 350",
        ],
    },
    {
        "name": "conveyor",
        "filename": "conveyor_a3.pdf",
        "drawing_number": "DWG-CON-002",
        "title": "CONVEYOR A3 SHEET 1",
        "subsystem_keyword": "Conveyor",
        "material": "MILD STEEL",
        "bom_lines": [
            "1  Conveyor Mild Steel 60 KG",
        ],
        "dimension_lines": [
            "BELT LENGTH 2000",
            "BELT WIDTH 400",
        ],
    },
    {
        "name": "compression_rollers",
        "filename": "compression_rollers_a3.pdf",
        "drawing_number": "DWG-CMP-003",
        "title": "COMPRESSION ROLLERS A3 SHEET 1",
        "subsystem_keyword": "CompressionRoller",
        "material": "STAINLESS 316",
        "bom_lines": [
            "2  CompressionRoller Stainless 12 KG",
        ],
        "dimension_lines": [
            "Ø 240 DIAMETER",
            "WIDTH 700",
            "Ø 50 SHAFT",
        ],
    },
    {
        "name": "drum",
        "filename": "drum_a3.pdf",
        "drawing_number": "DWG-DRM-004",
        "title": "DRUM A3 SHEET 1",
        "subsystem_keyword": "Drum",
        "material": "EN24T",
        "bom_lines": [
            "1  Drum En24t 380 KG",
        ],
        "dimension_lines": [
            "Ø 1500 DIAMETER",
            "LENGTH 2200",
            "12 THK WALL",
        ],
    },
    {
        "name": "spindle",
        "filename": "spindle_a3.pdf",
        "drawing_number": "DWG-SPN-005",
        "title": "SPINDLE A3 SHEET 1",
        "subsystem_keyword": "Spindle",
        "material": "EN24T",
        "bom_lines": [
            "1  Spindle En24t 95 KG",
        ],
        "dimension_lines": [
            "Ø 100 SHAFT",
            "Ø 280 FLIGHT",
            "LENGTH 1800",
        ],
    },
    {
        "name": "frame",
        "filename": "frame_a3.pdf",
        "drawing_number": "DWG-FRM-006",
        "title": "FRAME A3 SHEET 1",
        "subsystem_keyword": "Frame",
        "material": "MILD STEEL",
        "bom_lines": [
            "1  Frame Mild Steel 220 KG",
        ],
        "dimension_lines": [
            "RAIL LENGTH 3500",
            "RAIL WIDTH 1200",
            "10 THK PLATE",
        ],
    },
]


# ---------------------------------------------------------------------------
# PDF builder
# ---------------------------------------------------------------------------


def _build_pdf_bytes(title: str, text_lines: List[str]) -> bytes:
    """Build a minimal PDF 1.4 with the given lines
    embedded as text. The text is rendered with
    /F1 (Helvetica) at 12pt, each line 20pt below
    the previous, starting at (50, 750).

    The xref offsets are computed programmatically
    (not hand-stamped) so the builder scales to
    different text lengths.
    """
    # Build the content stream first so we can measure
    # its length and the object offsets.
    content_ops = ["BT", "/F1 12 Tf", "50 750 Td"]
    for i, line in enumerate(text_lines):
        # PDF text strings: escape ( ) \ and use \n for newlines
        escaped = (
            line.replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)")
        )
        if i == 0:
            content_ops.append(f"({escaped}) Tj")
        else:
            content_ops.append("0 -20 Td")
            content_ops.append(f"({escaped}) Tj")
    content_ops.append("ET")
    content_stream = "\n".join(content_ops) + "\n"
    # PDF text strings are byte strings; the existing
    # hand-stamped fixture (test_drawing_ingest_e2e.py::
    # MINIMAL_PDF_BYTES) uses latin-1 for special characters
    # like Ø (U+00D8). We match that here so pdfplumber
    # round-trips the dimension annotations correctly.
    content_bytes = content_stream.encode("latin-1")

    # Now build the object table. Track byte offsets
    # so we can write the xref table correctly.
    objects: List[bytes] = []

    def add(obj_bytes: bytes) -> int:
        """Append an object and return its 1-based id."""
        objects.append(obj_bytes)
        return len(objects)

    catalog_id = add(b"<< /Type /Catalog /Pages 2 0 R >>")
    pages_id = add(b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>")
    page_id = add(
        b"<< /Type /Page /Parent 2 0 R "
        b"/MediaBox [0 0 612 792] "
        b"/Contents 4 0 R "
        b"/Resources << /Font << /F1 5 0 R >> >> >>"
    )
    content_obj = (
        f"<< /Length {len(content_bytes)} >>\nstream\n".encode("ascii")
        + content_bytes
        + b"endstream"
    )
    content_id = add(content_obj)
    font_id = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")

    # Compose the file body, capturing object offsets
    # for the xref table.
    body = b"%PDF-1.4\n"
    offsets: Dict[int, int] = {}
    for idx, obj_bytes in enumerate(objects, start=1):
        offsets[idx] = len(body)
        body += f"{idx} 0 obj\n".encode("ascii") + obj_bytes + b"\nendobj\n"

    xref_offset = len(body)
    xref_lines = [f"xref\n0 {len(objects) + 1}\n",
                  "0000000000 65535 f \n"]
    for idx in range(1, len(objects) + 1):
        xref_lines.append(f"{offsets[idx]:010d} 00000 n \n")
    body += "".join(xref_lines).encode("ascii")
    body += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_offset}\n%%EOF\n"
    ).encode("ascii")

    return body


def _fixture_text_lines(fixture: Dict) -> List[str]:
    """Return the text lines to embed in a fixture PDF,
    shaped to trigger the OCR pipeline's parsers."""
    lines = [
        f"TITLE: {fixture['title']}",
        f"DWG.NO: {fixture['drawing_number']}",
        f"REV: A",
        f"MATERIAL: {fixture['material']}",
        f"DATE: 11/06/2026",
        "",
        "BILL OF MATERIALS:",
    ]
    lines.extend(fixture["bom_lines"])
    lines.append("")
    lines.append("DIMENSIONS:")
    lines.extend(fixture["dimension_lines"])
    return lines


# ---------------------------------------------------------------------------
# Sidecar builders
# ---------------------------------------------------------------------------


def _expected_graph(fixture: Dict) -> Dict:
    """The canonical MachineGraph the platform must
    produce for this fixture. Single-node graph
    (one subsystem per fixture) in the dict shape
    produced by ``SubsystemNode.to_dict()``.

    The regression test asserts the platform's actual
    graph is a **superset** of this sidecar's
    node_id keys (over-extraction allowed;
    under-extraction fails per spec §5.1).
    """
    node_id = fixture["name"]
    return {
        "name": fixture["title"].replace(" A3 SHEET 1", "").lower().replace(" ", "_"),
        "revision": "A",
        "nodes": {
            node_id: {
                "node_id": node_id,
                "node_type": node_id,
                "label": fixture["subsystem_keyword"],
                "config": {},
                "source": "drawing",
                "confidence": 0.85,
                "metadata": {},
            },
        },
        "edges": [],
    }


def _expected_score_placeholder() -> str:
    """The placeholder score sidecar. The maintainer
    must run the manual reference config through
    the orchestrator and replace this with the
    actual composite score minus 0.10 per spec §5.1.
    """
    return (
        "TBD\n"
        "# The maintainer must run the manual reference config\n"
        "# for this subsystem through the orchestrator and record\n"
        "# the composite score minus 0.10 per spec §5.1.\n"
        "# See docs/VALIDATION_PACK_METHODOLOGY.md for the\n"
        "# baselining protocol.\n"
    )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build_pack(target_dir: Path) -> int:
    """Build the 6 PDFs and 6 sidecar pairs in
    ``target_dir``. Returns the number of fixture
    files written (PDFs + sidecars = 18 total).
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    expected_dir = target_dir / "expected"
    expected_dir.mkdir(parents=True, exist_ok=True)

    written = 0
    for fixture in _SUBSYSTEM_FIXTURES:
        # Write the PDF.
        pdf_bytes = _build_pdf_bytes(
            fixture["title"],
            _fixture_text_lines(fixture),
        )
        pdf_path = target_dir / fixture["filename"]
        pdf_path.write_bytes(pdf_bytes)
        written += 1

        # Write the graph sidecar.
        graph_path = expected_dir / f"{fixture['name']}_a3.graph.json"
        graph_path.write_text(
            json.dumps(_expected_graph(fixture), indent=2)
            + "\n",
            encoding="utf-8",
        )
        written += 1

        # Write the score sidecar (placeholder).
        score_path = expected_dir / f"{fixture['name']}_a3.score.txt"
        score_path.write_text(
            _expected_score_placeholder(),
            encoding="utf-8",
        )
        written += 1

    return written


def main() -> int:
    """CLI entry point. Build the pack in
    ``tests/fixtures/drawings/`` (relative to the
    repository root)."""
    repo_root = Path(__file__).resolve().parents[2]
    target_dir = repo_root / "tests" / "fixtures" / "drawings"

    if not repo_root.exists():
        print(f"error: repo root not found at {repo_root}", file=sys.stderr)
        return 1

    written = build_pack(target_dir)
    print(
        f"Validation pack built: {written} files in {target_dir.relative_to(repo_root)}/"
    )
    print(
        "Note: expected/*_a3.score.txt files contain 'TBD' "
        "placeholders. The maintainer must baseline them by "
        "running the manual reference configs through the "
        "orchestrator per docs/VALIDATION_PACK_METHODOLOGY.md."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
